Fix #82, Convert integers holding boolean truth values to `bool`
nasa/CS pull request #83
Opened 2023-05-02 23:38 UTC by thnkslprpt

**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #82
  - 5 integer variables which only ever hold boolean truth values have been converted to `bool`

**Testing performed**
GitHub CI actions all passing successfully.

**Expected behavior changes**
No change to behavior.
- intent of these variables is more clear
- improved type-safety
- eases future maintainability

**Contributor Info**
Avi Weiss @thnkslprpt

2023-05-04 18:45 UTC, jphickey requested changes
We need to be sure that we don't change the tables or command message formats with this

2023-05-04 18:45 UTC, jphickey commented on fsw/inc/cs_msg.h
> +    bool    OneShotInProgress;           /**< \brief CS "OneShot In Progress" flag */
Things in "msg.h" affect inter-processor interfaces, so these should be limited should stay explicit about the width (i.e. keep using `uint8` here)

2023-05-04 18:45 UTC, jphickey commented on fsw/inc/cs_tbldefs.h
> +    bool    Filler8;            /** <\brief Padding */
Same comment here, this should stay as `uint16` to be explicit.  This file is an interface.

2023-09-29 14:11 UTC, jphickey requested changes
I think we still need to revert the changes to "cs_tbldefs.h" ....  Everything in this struct should be based on known-width types only - no "bool" or "cpuaddr".  So there were prexisting problems there.  But the proposed change will alter alignment and still uses bool and cpuaddr.  

The change to "cs_compute.c" is good though.

2023-09-30 04:41 UTC, thnkslprpt commented
> I think we still need to revert the changes to "cs_tbldefs.h" .... Everything in this struct should be based on known-width types only - no "bool" or "cpuaddr". So there were prexisting problems there. But the proposed change will alter alignment and still uses bool and cpuaddr.
> 
> The change to "cs_compute.c" is good though.

@jphickey No worries - I removed the changes to `cs_tbldefs.h` - unless you want me to remove the `bool`'s that are already in there?

2024-01-25 20:02 UTC, jphickey approved these changes

2024-02-08 19:15 UTC, merged